# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir ~/.m2/repository/com/cx/plugin/cli/9.20.0-SNAPSHOT
      cd ~/.m2/repository/com/cx/plugin/cli/9.20.0-SNAPSHOT
      ls
- task: S3Download@1
  inputs:
    awsCredentials: 'CxSLDC bucket'
    regionName: 'eu-west-1'
    bucketName: 'cxsdlc'
    globExpressions: '*9.20*.jar'
    targetFolder: '~/.m2/repository/com/cx/plugin/cli/9.20.0-SNAPSHOT'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd ~/work/1/a
      pwd
      ls
      cd ~/work/1/b
      pwd
      ls
      cd ~/work/1/s
      pwd
      ls

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false