# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more :
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


trigger:
  batch: true
  branches:
    include:
    - master

pool: 
  name: 'MyPcMajd'

steps:
- task: Application security testing@2020
  inputs:
    projectName: '123123'
    enableSastScan: true
    CheckmarxService: 'SAST1'
    fullTeamName: '\CxServer'
    enableDependencyScan: false
