# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 
  name: 'JenkinsPool'
  vmImage: 'jenkins-trigger'

steps:
- task: JenkinsQueueJob@2
  inputs:
    serverEndpoint: 'Locla TFS'
    jobName: 'sdfsf'
    captureConsole: true
    capturePipeline: true
    isParameterizedJob: true
    jobParameters: 'Commit=$(Build.SourceVersion)'
- task: S3Download@1
  inputs:
    awsCredentials: 'CxSLDC bucket'
    regionName: 'eu-west-1'
    bucketName: 'cxsdlc'
    globExpressions: '*9.20*.jar'
    targetFolder: ''
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mvn -v
      mvn install -e

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  condition: always()